server:
  port: 8080

app:
  jwt:
    secret: cd34182c15a3298b07f09eda397a6b131ec5d7c672dc470a3ce4aa767fe9d174
    expiresSeconds: 3600

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/bombtagnet?useSSL=false&allowPublicKeyRetrieval=true
    username: studyjun
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
    show-sql: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false